### ISSUE TITLE
HTML escaping issues

### ISSUE THREAD

**Issue by tomtom5152** [kelaresg/go-skype-bridge#1]
If a message contains a HTML escaped character, such as `&apos;`, the escaped version will be sent to the matrix home server resulting in some very difficult to understand messages at times, and it appears to also cause messages to vanish from the element iOS app (works fine on desktop)

P.S. great work otherwise though, one less native client I need to have running constantly

**Comment by tomtom5152** [comment]
I've just had time to take a little dig into the source of this but I'm struggling to navigate around where incoming messages are actually handled. I'm happy to attempt an unescaping implementation for this, using tests to simulate messages as the easiest way to reliably replicate it, but would need a point in the right direction of at least the file to look at.

**Comment by pidongqianqian** [comment]
oh glad you are willing to help improve this, these messages are processed and parsed here.
https://github.com/kelaresg/go-skype-bridge/blob/3c3ae50a1e37941d72b027cde07471c02ad935ce/portal.go#L1446
