### ISSUE TITLE
GET /_matrix/client/r0/account/whoami: M_FORBIDDEN (HTTP 403): Application service has not registered this user. 

### ISSUE THREAD

**Issue by xaionaro** [kelaresg/go-skype-bridge#7]
Hello. I did:
```
./matrix-skype -c config.yaml -g -r registration.yaml
```
added the path to this `registration.yaml` to `app_service_config_files` of `homeserver.yaml` and restarted the synapse daemon. Then I tried to execute the bridge, but I get:
```
[Feb 13, 2021 20:01:13] [DEBUG] Checking connection to homeserver
[Feb 13, 2021 20:01:13] [ERROR] Failed to connect to homeserver: failed to GET /_matrix/client/r0/account/whoami: M_FORBIDDEN (HTTP 403): Application service has not registered this user. Retrying in 10 seconds...
```
I'm wondering how to fix this?

**Comment by pidongqianqian** [comment]
It may be something wrong with your previous configuration, resulting in wrong database data. 
If you are in a test environment, you can try to delete both the synapse database and the bridge database, and then restart synapse first, then restart the bridge.

**Comment by xaionaro** [comment]
Thank you for the response. Unfortunately, I already fixed it somehow and forgot to write here...
